DELETE FROM programacao_evento
WHERE project_id = 'ge-triunfo-2026';
INSERT INTO programacao_evento (
        project_id,
        title,
        description,
        type,
        category,
        start_time,
        end_time,
        room,
        speakers,
        max_capacity,
        registered_count,
        color
    )
VALUES (
        'ge-triunfo-2026',
        'Credenciamento e Welcome Coffee',
        'Recepção dos participantes, entrega de kits e networking inicial.',
        'networking',
        'manha_ancora',
        '08:00',
        '08:30',
        'Salão Principal',
        ARRAY []::text [],
        0,
        0,
        'orange'
    ),
    (
        'ge-triunfo-2026',
        'Abertura Oficial: O Futuro da Inovação no Sertão',
        'Boas-vindas dos organizadores e visão estratégica para 2026.',
        'keynote',
        'manha_ancora',
        '08:30',
        '09:00',
        'Salão Principal',
        ARRAY ['Caio Borges', 'Autoridades Locais'],
        0,
        0,
        'orange'
    ),
    (
        'ge-triunfo-2026',
        'Palestra: Do Improviso ao Plano',
        'Como estruturar processos de crescimento em ambientes incertos.',
        'talk',
        'manha_bloco_1',
        '09:00',
        '10:00',
        'Salão Principal',
        ARRAY ['Leandro Batista'],
        0,
        0,
        'blue'
    ),
    (
        'ge-triunfo-2026',
        'Coffee Break & Networking',
        'Intervalo para conexões e visitação à área de negócios.',
        'networking',
        'manha_circulacao',
        '10:00',
        '10:15',
        'Área de Convivência',
        ARRAY []::text [],
        0,
        0,
        'green'
    ),
    (
        'ge-triunfo-2026',
        'Painel: Ecossistemas Regionais de Inovação',
        'Discussão sobre como fortalecer o empreendedorismo local.',
        'panel',
        'manha_bloco_2',
        '10:15',
        '11:45',
        'Salão Principal',
        ARRAY ['Representante SEBRAE', 'Investidor Convidado', 'Mediador'],
        0,
        0,
        'purple'
    ),
    (
        'ge-triunfo-2026',
        'Rodada de Negócios B2B - Sessão 1',
        'Reuniões pré-agendadas entre empresas âncoras e fornecedores.',
        'workshop',
        'tarde_bloco_3',
        '14:00',
        '15:30',
        'Espaço B2B',
        ARRAY []::text [],
        50,
        0,
        'orange'
    ),
    (
        'ge-triunfo-2026',
        'Arena Pitch: Demonstração de Startups',
        'Startups locais apresentam suas soluções para banca de investidores.',
        'circuito',
        'tarde_bloco_3',
        '14:00',
        '17:00',
        'Arena Pitches',
        ARRAY []::text [],
        100,
        0,
        'orange'
    ),
    (
        'ge-triunfo-2026',
        'Workshop: Marketing Digital para Negócios Locais',
        'Estratégias práticas para aumentar vendas usando canais digitais.',
        'workshop',
        'tarde_bloco_4',
        '15:45',
        '17:15',
        'Sala 01',
        ARRAY ['Especialista de Marketing'],
        30,
        0,
        'orange'
    ),
    (
        'ge-triunfo-2026',
        'Night Experience: Sunset & Networking',
        'Happy hour de encerramento com música ao vivo e networking premium.',
        'networking',
        'noturna',
        '18:00',
        '21:00',
        'Rooftop / Área Externa',
        ARRAY ['Artista Convidado'],
        0,
        0,
        'purple'
    ),
    (
        'ge-triunfo-2026',
        'Estação de Mentoria Flash',
        'Mentorias rápidas de 15 minutos com especialistas do hub.',
        'circuito',
        'circuito',
        '09:00',
        '17:00',
        'Espaço Circuito',
        ARRAY []::text [],
        0,
        0,
        'orange'
    );